#!/usr/bin/env python3
import argparse
import os
import re

from bot.analysis.analyzer import analyze_issue
from bot.config import load_config
from bot.github.client import GitHubClient
from bot.llm import EchoProvider, OpenAIProvider
from bot.patch.apply import apply_patch_in_temp
from bot.patch.diff import is_valid_unified_diff, trim_diff
from bot.patch.generator import generate_patch
from bot.pr.draft import create_draft_pr_from_diff
from bot.safety.score import compute_confidence
from bot.safety.tests import run_tests_in_temp


def parse_args():
    parser = argparse.ArgumentParser(description="AlphaPatch bot entry point")
    parser.add_argument("--repo", required=True, help="GitHub repository in owner/name form")
    parser.add_argument("--issue", required=True, help="Issue number or URL")
    return parser.parse_args()


def _parse_issue_number(value: str) -> int:
    if value.isdigit():
        return int(value)
    match = re.search(r"/issues/(\d+)", value)
    if match:
        return int(match.group(1))
    raise ValueError("--issue must be a number or issue URL")


def _select_provider(config):
    provider = config.llm_provider.lower()
    if provider == "openai":
        return OpenAIProvider(
            api_key=config.openai_api_key or "",
            model=config.openai_model or "",
            base_url=config.openai_base_url,
        )
    if provider == "echo":
        return EchoProvider()
    raise ValueError(f"Unsupported LLM_PROVIDER: {config.llm_provider}")


def _build_patch_section(repo_path: str, diff_text: str) -> tuple[str, bool]:
    if not diff_text.strip():
        return "**Patch Preview:** (no patch generated)", False

    if not is_valid_unified_diff(diff_text):
        return "**Patch Preview:** (model did not return a valid unified diff)", False

    applied, reason = apply_patch_in_temp(repo_path, diff_text)
    if not applied:
        return f"**Patch Preview:** (diff failed to apply in temp checkout: {reason})", False

    trimmed = trim_diff(diff_text)
    return "**Patch Preview:**\n\n```diff\n" + trimmed + "\n```", True


def _maybe_create_draft_pr(
    repo_path: str,
    repo: str,
    diff_text: str,
    issue_title: str,
    token: str,
) -> str:
    try:
        result = create_draft_pr_from_diff(
            repo_path=repo_path,
            repo=repo,
            diff_text=diff_text,
            title=f"AlphaPatch: {issue_title}",
            body="Automated draft PR generated by AlphaPatch.",
            token=token,
        )
        if result.pr_url:
            return f"Draft PR created: {result.pr_url}"
        return "Draft PR created."
    except Exception as exc:
        return f"Draft PR creation failed: {exc}"


def _format_test_section(tests_passed: bool | None, output: str) -> str:
    if tests_passed is None:
        return "**Tests:** (not run)"
    status = "passed" if tests_passed else "failed"
    if not output:
        return f"**Tests:** {status}"
    return (
        f"**Tests:** {status}\n\n"
        "<details><summary>Test output</summary>\n\n"
        "```\n" + output + "\n```\n"
        "</details>"
    )


def main():
    args = parse_args()
    issue_number = _parse_issue_number(args.issue)

    config = load_config()
    gh = GitHubClient(config.github_token)

    issue = gh.get_issue(args.repo, issue_number)

    provider = _select_provider(config)
    repo_path = os.getenv("GITHUB_WORKSPACE", os.getcwd())
    result = analyze_issue(issue, provider, repo_path)

    diff_text = generate_patch(issue, result["context_files"], provider)
    patch_section, patch_ok = _build_patch_section(repo_path, diff_text)

    tests_passed = None
    tests_output = ""
    if patch_ok and config.test_command:
        tests_passed, tests_output = run_tests_in_temp(
            repo_path,
            diff_text,
            config.test_command,
            config.test_timeout,
        )

    confidence_score, confidence_level = compute_confidence(diff_text, patch_ok, tests_passed)
    test_section = _format_test_section(tests_passed, tests_output)

    pr_note = ""
    if patch_ok and config.enable_draft_pr:
        if tests_passed is False:
            pr_note = "Draft PR skipped because tests failed."
        else:
            pr_note = _maybe_create_draft_pr(
                repo_path,
                args.repo,
                diff_text,
                issue.title,
                config.github_token,
            )

    label_note = ""
    if config.enable_labels:
        labels = [
            f"alphapatch:{result['classification']}",
            f"alphapatch:confidence-{confidence_level}",
        ]
        try:
            gh.add_labels(args.repo, issue_number, labels)
        except Exception as exc:
            label_note = f"Labeling failed: {exc}"

    body = (
        "AlphaPatch response:\n\n"
        f"**Classification:** {result['classification']}\n"
        f"**Summary:** {result['summary']}\n\n"
        f"{result['response']}\n\n"
        f"{patch_section}\n\n"
        f"**Confidence:** {confidence_score}/100 ({confidence_level})\n\n"
        f"{test_section}\n\n"
    )
    if pr_note:
        body += f"**PR:** {pr_note}\n\n"
    if label_note:
        body += f"**Labels:** {label_note}\n\n"
    body += "_To change the LLM provider, set `LLM_PROVIDER`._"

    gh.create_comment(args.repo, issue_number, body)


if __name__ == "__main__":
    main()
