#!/usr/bin/env python3
import argparse
import os
import re
import json

from bot.analysis.analyzer import analyze_issue
from bot.config import load_config, validate_config
from bot.github.client import GitHubClient
from bot.llm import EchoProvider, GeminiProvider, OpenAIProvider
from bot.patch.apply import apply_patch_in_temp
from bot.patch.diff import is_valid_unified_diff, trim_diff
from bot.patch.generator import generate_patch
from bot.pr.draft import create_draft_pr_from_diff
from bot.safety.score import compute_confidence
from bot.safety.tests import run_tests_in_temp
from bot.plugins.registry import (
    apply_after_analysis,
    apply_after_patch,
    apply_after_response,
    load_plugins,
)


def parse_args():
    parser = argparse.ArgumentParser(description="AlphaPatch bot entry point")
    parser.add_argument("--repo", required=False, help="GitHub repository in owner/name form")
    parser.add_argument("--issue", required=False, help="Issue number or URL")
    parser.add_argument("--event", required=False, help="Path to a GitHub event payload JSON")
    return parser.parse_args()


def _parse_issue_number(value: str) -> int:
    if value.isdigit():
        return int(value)
    match = re.search(r"/issues/(\d+)", value)
    if match:
        return int(match.group(1))
    raise ValueError("--issue must be a number or issue URL")


def _load_event_payload(path: str | None) -> dict | None:
    if not path:
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except OSError:
        return None


def _extract_issue_number_from_event(payload: dict | None) -> int | None:
    if not payload:
        return None
    if "issue" in payload and payload["issue"]:
        return payload["issue"].get("number")
    if "pull_request" in payload and payload["pull_request"]:
        return payload["pull_request"].get("number")
    return None


def _extract_comment_from_event(payload: dict | None) -> str | None:
    if not payload:
        return None
    comment = payload.get("comment") or {}
    body = comment.get("body")
    if not body:
        return None
    author = (comment.get("user") or {}).get("login") or "unknown"
    return f"Comment by {author}:\n{body}"


def _resolve_repo(args_repo: str | None) -> str:
    repo = args_repo or os.getenv("GITHUB_REPOSITORY")
    if not repo:
        raise ValueError("--repo is required (or set GITHUB_REPOSITORY)")
    return repo


def _select_provider(config):
    provider = config.llm_provider.lower()
    if provider == "openai":
        return OpenAIProvider(
            api_key=config.openai_api_key or "",
            model=config.openai_model or "",
            base_url=config.openai_base_url,
        )
    if provider == "gemini":
        return GeminiProvider(
            api_key=config.gemini_api_key or "",
            model=config.gemini_model or "",
            base_url=config.gemini_base_url,
        )
    if provider == "echo":
        return EchoProvider()
    raise ValueError(f"Unsupported LLM_PROVIDER: {config.llm_provider}")


def _build_patch_section(repo_path: str, diff_text: str) -> tuple[str, bool, str]:
    if not diff_text.strip():
        return "**Patch Preview:** (no patch generated)", False, "empty diff"

    if not is_valid_unified_diff(diff_text):
        return "**Patch Preview:** (model did not return a valid unified diff)", False, "invalid diff"

    applied, reason = apply_patch_in_temp(repo_path, diff_text)
    if not applied:
        return (
            f"**Patch Preview:** (diff failed to apply in temp checkout: {reason})",
            False,
            f"apply failed: {reason}",
        )

    trimmed = trim_diff(diff_text)
    return "**Patch Preview:**\n\n```diff\n" + trimmed + "\n```", True, ""


def _maybe_create_draft_pr(
    repo_path: str,
    repo: str,
    diff_text: str,
    issue_title: str,
    token: str,
) -> str:
    try:
        result = create_draft_pr_from_diff(
            repo_path=repo_path,
            repo=repo,
            diff_text=diff_text,
            title=f"AlphaPatch: {issue_title}",
            body="Automated draft PR generated by AlphaPatch.",
            token=token,
        )
        if result.pr_url:
            return f"Draft PR created: {result.pr_url}"
        return "Draft PR created."
    except Exception as exc:
        return f"Draft PR creation failed: {exc}"


def _format_test_section(tests_passed: bool | None, output: str) -> str:
    if tests_passed is None:
        return "**Tests:** (not run)"
    status = "passed" if tests_passed else "failed"
    if not output:
        return f"**Tests:** {status}"
    return (
        f"**Tests:** {status}\n\n"
        "<details><summary>Test output</summary>\n\n"
        "```\n" + output + "\n```\n"
        "</details>"
    )


def main():
    args = parse_args()
    payload = _load_event_payload(args.event or os.getenv("GITHUB_EVENT_PATH"))
    issue_number = None
    if args.issue:
        issue_number = _parse_issue_number(args.issue)
    else:
        issue_number = _extract_issue_number_from_event(payload)
    if issue_number is None:
        raise ValueError("Issue number is required (--issue or event payload)")

    config = load_config()
    validate_config(config)
    gh = GitHubClient(config.github_token)
    plugins = load_plugins(config.plugin_dir) if config.plugins_enabled else []

    repo = _resolve_repo(args.repo)
    issue = gh.get_issue(repo, issue_number)
    comment_context = _extract_comment_from_event(payload)
    if comment_context:
        issue = issue.__class__(
            number=issue.number,
            title=issue.title,
            body=f"{issue.body}\n\n---\n{comment_context}",
            url=issue.url,
            author=issue.author,
        )

    provider = _select_provider(config)
    repo_path = os.getenv("GITHUB_WORKSPACE", os.getcwd())
    result = analyze_issue(issue, provider, repo_path)
    if plugins:
        result = apply_after_analysis(plugins, result)

    diff_text = generate_patch(issue, result["context_files"], provider)
    if plugins:
        diff_text = apply_after_patch(plugins, diff_text)
    patch_section, patch_ok, patch_reason = _build_patch_section(repo_path, diff_text)
    attempt = 1
    while not patch_ok and attempt < config.patch_retry_attempts:
        feedback = f"Attempt {attempt} failed: {patch_reason}"
        diff_text = generate_patch(issue, result["context_files"], provider, feedback=feedback)
        patch_section, patch_ok, patch_reason = _build_patch_section(repo_path, diff_text)
        attempt += 1

    tests_passed = None
    tests_output = ""
    if patch_ok and config.test_command:
        tests_passed, tests_output = run_tests_in_temp(
            repo_path,
            diff_text,
            config.test_command,
            config.test_timeout,
        )

    confidence_score, confidence_level = compute_confidence(diff_text, patch_ok, tests_passed)
    test_section = _format_test_section(tests_passed, tests_output)

    pr_note = ""
    if patch_ok and config.enable_draft_pr:
        if tests_passed is False:
            pr_note = "Draft PR skipped because tests failed."
        else:
            pr_note = _maybe_create_draft_pr(
                repo_path,
                repo,
                diff_text,
                issue.title,
                config.github_token,
            )

    label_note = ""
    if config.enable_labels:
        labels = [
            f"alphapatch:{result['classification']}",
            f"alphapatch:confidence-{confidence_level}",
        ]
        try:
            gh.add_labels(repo, issue_number, labels)
        except Exception as exc:
            label_note = f"Labeling failed: {exc}"

    response_text = result["response"]
    if plugins:
        response_text = apply_after_response(plugins, response_text)

    body = (
        "AlphaPatch response:\n\n"
        f"**Classification:** {result['classification']}\n"
        f"**Language:** {result['language']}\n"
        f"**Summary:** {result['summary']}\n\n"
        f"{response_text}\n\n"
        f"{patch_section}\n\n"
        f"**Confidence:** {confidence_score}/100 ({confidence_level})\n\n"
        f"{test_section}\n\n"
    )
    if pr_note:
        body += f"**PR:** {pr_note}\n\n"
    if label_note:
        body += f"**Labels:** {label_note}\n\n"
    body += "_To change the LLM provider, set `LLM_PROVIDER`._"

    gh.create_comment(repo, issue_number, body)


if __name__ == "__main__":
    main()
